config/routes.rb
Rails.application.routes.draw do

  
  
  root 'access#login'
  get 'home' => 'home#index'
  
  get 'attempt_login' => 'access#attempt_login'
  post 'attempt_login' => 'access#attempt_login'
  get '/dashboard' => 'dashboard#index'
  post  'logout' => 'home#logout'
  get  'logout' => 'home#logout'
  resources :disciplinas
  resources :associaziones
  resources :tutors
  resources :bambinos
  resources :allenatores
  resources :coordinatores
  resources :segnalatores
  
  

end

app/models/associazione.rb
class Associazione < ActiveRecord::Base

	has_many :bambinos
	has_many :allenatores

	validates_presence_of :ragione_sociale
	
	
	def città=(value)
  	write_attribute(:città, value.capitalize)
	end

end

app/controllers/associaziones_controller.rb
class AssociazionesController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_associazione, only: [:show, :edit, :update, :destroy]

  # GET /associaziones
  # GET /associaziones.json
  def index
    @associaziones = Associazione.all
  end

  # GET /associaziones/1
  # GET /associaziones/1.json
  def show
  end

  # GET /associaziones/new
  def new
    @associazione = Associazione.new
  end

  # GET /associaziones/1/edit
  def edit
  end

  # POST /associaziones
  # POST /associaziones.json
  def create
    @associazione = Associazione.new(associazione_params)

    respond_to do |format|
      if @associazione.save
        format.html { redirect_to @associazione, notice: 'Associazione was successfully created.' }
        format.json { render :show, status: :created, location: @associazione }
      else
        format.html { render :new }
        format.json { render json: @associazione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associaziones/1
  # PATCH/PUT /associaziones/1.json
  def update
    respond_to do |format|
      if @associazione.update(associazione_params)
        format.html { redirect_to @associazione, notice: 'Associazione was successfully updated.' }
        format.json { render :show, status: :ok, location: @associazione }
      else
        format.html { render :edit }
        format.json { render json: @associazione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associaziones/1
  # DELETE /associaziones/1.json
  def destroy
    @associazione.destroy
    respond_to do |format|
      format.html { redirect_to associaziones_url, notice: 'Associazione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associazione
      @associazione = Associazione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associazione_params
      params.require(:associazione).permit(:ragione_sociale, :indirizzo, :città, :manifesto)
    end
end

app/helpers/associaziones_helper.rb
module AssociazionesHelper
end

app/views/associaziones/_form.html.erb
<%= bootstrap_form_for(@associazione) do |f| %>
  <% if @associazione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@associazione.errors.count, "error") %> prohibited this associazione from being saved:</h2>

      <ul>
      <% @associazione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :ragione_sociale %>
  </div>
  <div class="field">
    
    <%= f.text_field :indirizzo %>
  </div>
  <div class="field">
 
    <%= f.text_field :città %>
  </div>
 <div class="field">
 
    <%= f.check_box :manifesto %>
  </div>
  <div class="actions">
    <%= f.submit 'Aggiungi associazione', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/associaziones/edit.html.erb
<h1>Editing Associazione</h1>

<%= render 'form' %>

<%= link_to 'Show', @associazione %> |
<%= link_to 'Back', associaziones_path %>

app/views/associaziones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Associazioni SSF</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Ragione sociale</th>
      <th>Indirizzo</th>
      <th>Città</th>
      <th>Manifesto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associaziones.each do |associazione| %>
      <tr>
        <td><%= associazione.ragione_sociale %></td>
        <td><%= associazione.indirizzo %></td>
        <td><%= associazione.città %></td>
        <% if associazione.manifesto %>
        <td>SI</td>
        <% else %>
        <td>NO</td>
        <% end %>
        <td><%= link_to 'Show', associazione %></td>
        <td><%= link_to 'Edit', edit_associazione_path(associazione) %></td>
        <td><%= link_to 'Destroy', associazione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi associazione', new_associazione_path %>

app/views/associaziones/new.html.erb
<center>
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
<h1>Nuova Associazione</h1>

<%= render 'form' %>

<%= link_to 'Elenco associazioni', associaziones_path %>
		</div>
	</div>
</center>

app/views/associaziones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ragione sociale:</strong>
  <%= @associazione.ragione_sociale %>
</p>

<p>
  <strong>Indirizzo:</strong>
  <%= @associazione.indirizzo %>
</p>

<p>
  <strong>Città:</strong>
  <%= @associazione.città %>
</p>

<p>
  <strong>Città:</strong>
  <%= @associazione.manifesto %>
</p>

<%= link_to 'Edit', edit_associazione_path(@associazione) %> |
<%= link_to 'Back', associaziones_path %>