config/routes.rb
Rails.application.routes.draw do

  
  
  root 'access#login'
  get 'home' => 'home#index'
  
  get 'attempt_login' => 'access#attempt_login'
  post 'attempt_login' => 'access#attempt_login'
  get '/dashboard' => 'dashboard#index'
  post  'logout' => 'home#logout'
  get  'logout' => 'home#logout'
  resources :disciplinas
  resources :associaziones
  resources :tutors
  resources :bambinos
  resources :allenatores
  resources :coordinatores
  resources :segnalatores
  
  

end

app/models/allenatore.rb
class Allenatore < ActiveRecord::Base
  belongs_to :associazione
  has_many :bambinos

  validates_presence_of :nome,:cognome,:associazione_id

  def nome=(value)
  	write_attribute(:nome,value.capitalize)
  end
  def cognome=(value)
  	write_attribute(:cognome,value.capitalize)
  end

end

app/controllers/allenatores_controller.rb
class AllenatoresController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_allenatore, only: [:show, :edit, :update, :destroy]

  # GET /allenatores
  # GET /allenatores.json
  def index
    @allenatores = Allenatore.all
  end

  # GET /allenatores/1
  # GET /allenatores/1.json
  def show
  end

  # GET /allenatores/new
  def new
    @allenatore = Allenatore.new
  end

  # GET /allenatores/1/edit
  def edit
  end

  # POST /allenatores
  # POST /allenatores.json
  def create
    @allenatore = Allenatore.new(allenatore_params)

    respond_to do |format|
      if @allenatore.save
        format.html { redirect_to @allenatore, notice: 'Allenatore was successfully created.' }
        format.json { render :show, status: :created, location: @allenatore }
      else
        format.html { render :new }
        format.json { render json: @allenatore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allenatores/1
  # PATCH/PUT /allenatores/1.json
  def update
    respond_to do |format|
      if @allenatore.update(allenatore_params)
        format.html { redirect_to @allenatore, notice: 'Allenatore was successfully updated.' }
        format.json { render :show, status: :ok, location: @allenatore }
      else
        format.html { render :edit }
        format.json { render json: @allenatore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allenatores/1
  # DELETE /allenatores/1.json
  def destroy
    @allenatore.destroy
    respond_to do |format|
      format.html { redirect_to allenatores_url, notice: 'Allenatore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allenatore
      @allenatore = Allenatore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allenatore_params
      params.require(:allenatore).permit(:nome, :cognome, :telefono, :email, :associazione_id)
    end
end

app/helpers/allenatores_helper.rb
module AllenatoresHelper
end

app/views/allenatores/_form.html.erb
<%= bootstrap_form_for(@allenatore) do |f| %>
  <% if @allenatore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allenatore.errors.count, "error") %> prohibited this allenatore from being saved:</h2>

      <ul>
      <% @allenatore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    
    <%= f.text_field :cognome %>
  </div>
  <div class="field">
    
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
   
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.collection_select( :associazione_id, Associazione.all, :id, :ragione_sociale, {}, {:multiple => false}) %>
  </div>
  <div class="actions">
    <%= f.submit 'Aggiungi allenatore', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/allenatores/edit.html.erb
<h1>Editing Allenatore</h1>

<%= render 'form' %>

<%= link_to 'Show', @allenatore %> |
<%= link_to 'Back', allenatores_path %>

app/views/allenatores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Allenatori SSF</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cognome</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Associazione</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @allenatores.each do |allenatore| %>
      <tr>
        <td><%= allenatore.nome %></td>
        <td><%= allenatore.cognome %></td>
        <td><%= allenatore.telefono %></td>
        <td><%= allenatore.email %></td>
        <td><%= allenatore.associazione.ragione_sociale %></td>
        <td><%= link_to 'Show', allenatore %></td>
        <td><%= link_to 'Edit', edit_allenatore_path(allenatore) %></td>
        <td><%= link_to 'Destroy', allenatore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi allenatore', new_allenatore_path %>

app/views/allenatores/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	<h1>Aggiungi Allenatore</h1>

	<%= render 'form' %>

	<%= link_to 'Elenco allenatori', allenatores_path %>
	</div>
</div>

app/views/allenatores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @allenatore.nome %>
</p>

<p>
  <strong>Cognome:</strong>
  <%= @allenatore.cognome %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @allenatore.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @allenatore.email %>
</p>

<p>
  <strong>Associazione:</strong>
  <%= @allenatore.associazione.ragione_sociale %>
</p>

<%= link_to 'Edit', edit_allenatore_path(@allenatore) %> |
<%= link_to 'Back', allenatores_path %>