config/routes.rb
Rails.application.routes.draw do

  
  
  root 'access#login'
  get 'home' => 'home#index'
  
  get 'attempt_login' => 'access#attempt_login'
  post 'attempt_login' => 'access#attempt_login'
  get '/dashboard' => 'dashboard#index'
  post  'logout' => 'home#logout'
  get  'logout' => 'home#logout'
  resources :disciplinas
  resources :associaziones
  resources :tutors
  resources :bambinos
  resources :allenatores
  resources :coordinatores
  resources :segnalatores
  
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base



	has_secure_password

	validates_presence_of :username, :password
	validates_uniqueness_of  :username
	
end

app/models/allenatore.rb
class Allenatore < ActiveRecord::Base
  belongs_to :associazione
  has_many :bambinos

  validates_presence_of :nome,:cognome,:associazione_id

  def nome=(value)
  	write_attribute(:nome,value.capitalize)
  end
  def cognome=(value)
  	write_attribute(:cognome,value.capitalize)
  end

end

app/models/associazione.rb
class Associazione < ActiveRecord::Base

	has_many :bambinos
	has_many :allenatores

	validates_presence_of :ragione_sociale
	
	
	def città=(value)
  	write_attribute(:città, value.capitalize)
	end

end

app/models/bambino.rb
class Bambino < ActiveRecord::Base
    
    belongs_to :tutor
    belongs_to :associazione
    belongs_to :allenatore
    belongs_to :coordinatore
    belongs_to :segnalatore

    validates_presence_of  :nome, :cognome

	def nome=(value)
  	write_attribute(:nome, value.capitalize)
	end

	def cognome=(value)
  	write_attribute(:cognome, value.capitalize)
	end

	def cittadinanza=(value)
  	write_attribute(:cittadinanza, value.capitalize)
	end
	def disciplina=(value)
  	write_attribute(:disciplina, value.downcase)
	end
end

app/models/coordinatore.rb
class Coordinatore < ActiveRecord::Base

	has_many :bambinos

	def nome=(value)
  	write_attribute(:nome,value.capitalize)
	end
  	def cognome=(value)
  	write_attribute(:cognome,value.capitalize)
  	end


end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base

	validates_presence_of :disciplina_sportiva

	def disciplina_sportiva=(value)

		write_attribute(:disciplina_sportiva, value.downcase)

	end
end

app/models/segnalatore.rb
class Segnalatore < ActiveRecord::Base

	has_many :bambinos
	
	validates_presence_of :ente
	
	
	def città=(value)
  	write_attribute(:città, value.capitalize)
	end

end

app/models/tutor.rb
class Tutor < ActiveRecord::Base

	has_many :bambinos

	validates_presence_of  :nome, :cognome

	def nome=(value)
  	write_attribute(:nome, value.capitalize)
	end

	def cognome=(value)
  	write_attribute(:cognome, value.capitalize)
	end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :attempt_login]

  def login
  end

  def attempt_login
  	if params[:username].present? && params[:password].present?
  		found_user = AdminUser.where(:username => params[:username]).first
  	if found_user
  		authorized_user = found_user.authenticate(params[:password])
  	end
  	end
  	if authorized_user
  	session[:user_id] = authorized_user.id
  	session[:username] = authorized_user.username
  	flash[:notice] = 'You are logged in'
  	redirect_to home_path
  	else
  	
  	redirect_to(:action => 'login')
 	 end

  end

  


end

app/controllers/coordinatores_controller.rb
class CoordinatoresController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_coordinatore, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @coordinatores = Coordinatore.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @coordinatore = Coordinatore.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @coordinatore = Coordinatore.new(coordinatore_params)

    respond_to do |format|
      if @coordinatore.save
        format.html { redirect_to @coordinatore, notice: 'Coordinatore was successfully created.' }
        format.json { render :show, status: :created, location: @coordinatore }
      else
        format.html { render :new }
        format.json { render json: @coordinatore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @coordinatore.update(coordinatore_params)
        format.html { redirect_to @coordinatore, notice: 'Coordinatore was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinatore }
      else
        format.html { render :edit }
        format.json { render json: @coordinatore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @coordinatore.destroy
    respond_to do |format|
      format.html { redirect_to coordinatores_url, notice: 'Coordinatore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinatore
      @coordinatore = Coordinatore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coordinatore_params
      params.require(:coordinatore).permit(:nome, :cognome, :email, :telefono)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end


def logout
	session[:user_id] = nil
  	session[:username] = nil
  	redirect_to root_path
end



end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:nome, :cognome, :email, :telefono)
    end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/allenatores_helper.rb
module AllenatoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associaziones_helper.rb
module AssociazionesHelper
end

app/helpers/bambinos_helper.rb
module BambinosHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/segnalatores_helper.rb
module SegnalatoresHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/coordinatores/_form.html.erb
<%= bootstrap_form_for @coordinatore, :html => {class: 'form'} do |f| %>
  <% if @coordinatore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% @coordinatore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
<div class="form-group">
    
    <%= f.text_field :nome %>
  </div>
  <div class="form-group">
   
    <%= f.text_field :cognome %>
  </div>
  <div class="form-group">
    
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    
    <%= f.text_field :telefono %>
  </div>
  <div class="form-group">
    <%= f.submit 'Aggiungi Coordinatore', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/coordinatores/edit.html.erb
<h1>Editing Coordinatore</h1>

<%= render 'form' %>

<%= link_to 'Show', @coordinatore %> |
<%= link_to 'Back', coordinatores_path %>

app/views/coordinatores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coordinatori SSF</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cognome</th>
      <th>Email</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinatores.each do |coordinatore| %>
      <tr>
        <td><%= coordinatore.nome %></td>
        <td><%= coordinatore.cognome %></td>
        <td><%= coordinatore.email %></td>
        <td><%= coordinatore.telefono %></td>
        <td><%= link_to 'Show', coordinatore %></td>
        <td><%= link_to 'Edit', edit_coordinatore_path(coordinatore) %></td>
        <td><%= link_to 'Destroy', coordinatore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi coordinatore', new_coordinatore_path %>

app/views/coordinatores/new.html.erb
<center>
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<h1>Aggiungi Coordinatore</h1>

			<%= render 'form' %>

			<%= link_to 'Lista Coordinatori', coordinatores_path %>

		</div>	
	</div>
</cente

app/views/coordinatores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @coordinatore.nome %>
</p>

<p>
  <strong>Cognome:</strong>
  <%= @coordinatore.cognome %>
</p>

<p>
  <strong>Data di nascita:</strong>
  <%= @coordinatore.email %>
</p>

<p>
  <strong>Luogo di nascita:</strong>
  <%= @coordinatore.telefono %>
</p>


<%= link_to 'Edit', edit_coordinatore_path(@coordinatore) %> |
<%= link_to 'Back', coordinatores_path %>