config/routes.rb
Rails.application.routes.draw do

  
  
  root 'access#login'
  get 'home' => 'home#index'
  
  get 'attempt_login' => 'access#attempt_login'
  post 'attempt_login' => 'access#attempt_login'
  get '/dashboard' => 'dashboard#index'
  post  'logout' => 'home#logout'
  get  'logout' => 'home#logout'
  resources :disciplinas
  resources :associaziones
  resources :tutors
  resources :bambinos
  resources :allenatores
  resources :coordinatores
  resources :segnalatores
  
  

end

app/models/bambino.rb
class Bambino < ActiveRecord::Base
    
    belongs_to :tutor
    belongs_to :associazione
    belongs_to :allenatore
    belongs_to :coordinatore
    belongs_to :segnalatore

    validates_presence_of  :nome, :cognome

	def nome=(value)
  	write_attribute(:nome, value.capitalize)
	end

	def cognome=(value)
  	write_attribute(:cognome, value.capitalize)
	end

	def cittadinanza=(value)
  	write_attribute(:cittadinanza, value.capitalize)
	end
	def disciplina=(value)
  	write_attribute(:disciplina, value.downcase)
	end
end

app/controllers/bambinos_controller.rb
class BambinosController < ApplicationController
  before_action :confirm_logged_in
  before_action  :set_bambino, only: [:show, :edit, :update, :destroy]

  # GET /bambinos
  # GET /bambinos.json
  def index
    @bambinos = Bambino.all
  end

  # GET /bambinos/1
  # GET /bambinos/1.json
  def show
  end

  # GET /bambinos/new
  def new
    @bambino = Bambino.new
  end

  # GET /bambinos/1/edit
  def edit
  end

  # POST /bambinos
  # POST /bambinos.json
  def create
    @bambino = Bambino.new(bambino_params)

    respond_to do |format|
      if @bambino.save
        format.html { redirect_to @bambino, notice: 'Bambino was successfully created.' }
        format.json { render :show, status: :created, location: @bambino }
      else
        format.html { render :new }
        format.json { render json: @bambino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bambinos/1
  # PATCH/PUT /bambinos/1.json
  def update
    respond_to do |format|
      if @bambino.update(bambino_params)
        format.html { redirect_to @bambino, notice: 'Bambino was successfully updated.' }
        format.json { render :show, status: :ok, location: @bambino }
      else
        format.html { render :edit }
        format.json { render json: @bambino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bambinos/1
  # DELETE /bambinos/1.json
  def destroy
    @bambino.destroy
    respond_to do |format|
      format.html { redirect_to bambinos_url, notice: 'Bambino was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bambino
      @bambino = Bambino.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bambino_params
      params.require(:bambino).permit(:nome, 
        :cognome, 
        :data_di_nascita, 
        :luogo_di_nascita,
        :genere, 
        :status, 
        :cittadinanza, 
        :disciplina, 
        :associazione_id, 
        :tutor_id, 
        :allenatore_id, 
        :data_inserimento,
        :situazione_abitativa,
        :nome_madre,
        :cognome_madre,
        :nome_padre,
        :cognome_padre,
        :fine_inserimento,
        :coordinatore_id,
        :riferimento_telefonico,
        :segnalatore_id)
    end
end

app/helpers/bambinos_helper.rb
module BambinosHelper
end

app/views/bambinos/_form.html.erb
<%= bootstrap_form_for(@bambino)  do |f| %>
  <% if @bambino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bambino.errors.count, "error") %> prohibited this bambino from being saved:</h2>

      <ul>
      <% @bambino.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  
    <div class="row">
    <div class="col-md-3">
    <%= f.text_field :nome %>
  
    <%= f.text_field :cognome %>

    <%= f.date_select :data_di_nascita, :start_year => 1995  %>
    <%= f.select(:genere, options_for_select([
      ['M','M'],
      ['F','F']
      ]),
      selected: f.object.genere
      ) %>

    <%= f.text_field :luogo_di_nascita %>

    <%= f.select(:status,
     options_for_select([
      ['segnalato','segnalato'],
      ['inserito','inserito'],
      ['drop','drop'],
      ['concluso','concluso']
      ]),
      selected: f.object.status
      ) %>
    <%= f.select(:situazione_abitativa, options_for_select([
      ['affitto','affitto'],
      ['occupazione','occupazione'],
      ['casa popolare','casa popolare'],
      ['casa di proprietà','casa di proprietà'],
      ['centro di accoglienza', 'centro di accoglienza'],
      ['casa famiglia','casa famiglia']
      ]),
      selected: f.object.situazione_abitativa
      ) %>

    </div>
    <div class="col-md-3">

    <%= f.text_field :cittadinanza %> 
    <p>(Inserire paese. Es: Italia, no italiano)</p>
    <%= f.text_field :disciplina %>
  
    <%= f.collection_select( :associazione_id, Associazione.all, :id, :ragione_sociale, {}, {:multiple => false}) %>

    <%= f.collection_select( :coordinatore_id, Coordinatore.all, :id, :cognome, {:include_blank => true}, {:multiple => false}) %>
    
    <%= f.collection_select( :tutor_id, Tutor.all, :id, :cognome, {:include_blank => true}, {:multiple => false }) %>

    <%= f.collection_select( :allenatore_id, Allenatore.all, :id, :cognome, {:include_blank => true}, {:multiple => false}) %>
    
    </div>
    <div class="col-md-3">
       <%= f.text_field :nome_madre %>
       <%= f.text_field :cognome_madre %>
       <%= f.text_field :nome_padre %>
       <%= f.text_field :cognome_padre %>
       <%= f.date_select :data_inserimento, :start_year => 2011  %>
       <%= f.date_select :fine_inserimento, {:include_blank => true, :default => nil} %>
    </div>
    <div class="col-md-3">
       <%= f.text_field :riferimento_telefonico %>
      <%= f.collection_select( :segnalatore_id, Segnalatore.all, :id, :ente, {:include_blank => true}, {:multiple => false}) %>
    </div>
    </div>
    <div class="text-center">
    <%= f.submit 'Aggiungi bambino', class: "btn btn-lg btn-primary" %>
    </div>

  <% end %>
  

app/views/bambinos/edit.html.erb
<h1>Editing Bambino</h1>

<%= render 'form' %>

<%= link_to 'Show', @bambino %> |
<%= link_to 'Back', bambinos_path %>

app/views/bambinos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bambini SSF</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cognome</th>
      <th>Data di nascita</th>
      <th>Luogo di nascita</th>
      <th>Status</th>
      <th>Cittadinanza</th>
      <th>Disciplina</th>
      <th>Associazione</th>
      <th>Coordinatore</th>
      <th>Tutor</th>
      <th>Data inserimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bambinos.each do |bambino| %>
      <tr>
        <td><%= bambino.nome %></td>
        <td><%= bambino.cognome %></td>
        <td><%= bambino.data_di_nascita.strftime('%d-%m-%Y') %></td>
        <td><%= bambino.luogo_di_nascita %></td>
        <td><%= bambino.status %></td>
        <td><%= bambino.cittadinanza %></td>
        <td><%= bambino.disciplina %></td>
         <td><%= bambino.associazione.ragione_sociale %></td>
        <td><%= bambino.coordinatore.try(:cognome).blank? ? 'N/A' : bambino.coordinatore.cognome %></td>
         <td><%= bambino.tutor.try(:cognome).blank? ? 'N/A' : bambino.tutor.cognome %></td>
        <td><%= bambino.data_inserimento %></td>
        <td><%= link_to 'Show', bambino %></td>
        <td><%= link_to 'Edit', edit_bambino_path(bambino) %></td>
        <td><%= link_to 'Destroy', bambino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi Bambino', new_bambino_path %>

app/views/bambinos/new.html.erb
<center><h2 id="aggiungiBambino">Aggiungi Bambino</h2></center>

<%= render 'form' %>

<h4><%= link_to 'Elenco bambini', bambinos_path %></h4>

app/views/bambinos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
<p>
  <strong>Nome:</strong>
  <%= @bambino.nome %>
</p>

<p>
  <strong>Cognome:</strong>
  <%= @bambino.cognome %>
</p>
<p>
  <strong>Genere:</strong>
  <%= @bambino.genere %>
</p>

<p>
  <strong>Data di nascita:</strong>
  <%= @bambino.data_di_nascita %>
</p>

<p>
  <strong>Luogo di nascita:</strong>
  <%= @bambino.luogo_di_nascita %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bambino.status %>
</p>

<p>
  <strong>Cittadinanza:</strong>
  <%= @bambino.cittadinanza %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @bambino.disciplina %>
</p>

<p>
  <strong>Associazione:</strong>
  <%= @bambino.associazione.ragione_sociale %>
</p>
<p>
  <strong>Coordinatore:</strong>
  <%= @bambino.coordinatore_id %>
</p>
<p>
  <strong>Tutor:</strong>
  <%= @bambino.tutor.cognome %>
</p>
<p>
  <strong>Data Inserimento:</strong>
  <%= @bambino.data_inserimento %>
</p>
<p>
  <strong>Situazione abitativa:</strong>
  <%= @bambino.situazione_abitativa %>
</p>
<p>
  <strong>Nome madre:</strong>
  <%= @bambino.nome_madre %>
</p>
<p>
  <strong>Cognome madre:</strong>
  <%= @bambino.cognome_madre %>
</p>
<p>
  <strong>Nome padre:</strong>
  <%= @bambino.nome_padre %>
</p>
<p>
  <strong>Cognome padre:</strong>
  <%= @bambino.cognome_padre %>
</p>
<p>
  <strong>Ente segnalatore:</strong>
  <%= @bambino.segnalatore.ente %>
</p>

<%= link_to 'Edit', edit_bambino_path(@bambino) %> |
<%= link_to 'Back', bambinos_path %>
</div>
</div>